language: java

script: ./gradlew build

deploy:
  provider: releases
  api_key: 
    secure: $GITHUB_TOKEN_JOHN
  file_glob: true
  file: build/**/*
  skip_cleanup: true
  on:
    branch: john
    tags: true
